database:
    name: Remote Backend
    type: remote-backend
    host: "127.0.0.1:4242"

#database:
#    name: Local RocksDB
#    type: rocksdb
#    db_path: /tmp/balboa

#database:
#    name: Local Cassandra
#    type: cassandra
#    hosts: [ "127.0.0.1", "127.0.0.2", "127.0.0.3" ]
